Vagrant.configure("2") do |config|
  config.vm.box = "windows10"
  config.vm.guest = :windows

  config.vm.communicator = "winrm"

  config.winrm.username = "IEUser"
  config.winrm.password = "Passw0rd!"

  config.winrm.timeout =   1800
  config.vm.boot_timeout = 1800

  config.vm.provider "virtualbox" do |vb|
     vb.name = "Windows10"
     vb.gui = true
   end
end