Vagrant.configure("2") do |config|
  config.vm.box = "windows10"
  config.vm.guest = :windows

  config.vm.communicator = "winrm"

  config.winrm.username = "victim"
  config.winrm.password = "vagrant"

  config.vm.provider "virtualbox" do |vb|
     vb.name = "Windows10"
     vb.gui = true
   end
end


